<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>NewsByTheMood.MVC.Program</StartupObject>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NewsByTheMood.Core\NewsByTheMood.Core.csproj" />
    <ProjectReference Include="..\NewsByTheMood.MVC.Models\NewsByTheMood.MVC.Models.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.DataProvider\NewsByTheMood.Services.DataProvider.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.EmailProvider\NewsByTheMood.Services.EmailProvider.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.FileProvider\NewsByTheMood.Services.FileProvider.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.Mappers\NewsByTheMood.Services.Mappers.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.ArticleProccessingService\NewsByTheMood.Services.ArticleProccessingService.csproj" />
    <ProjectReference Include="..\NewsByTheMood.Services.PositifityRater\NewsByTheMood.Services.PositivityRater.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\storage\usericons\" />
  </ItemGroup>

  <ProjectExtensions>
    <VisualStudio>
      <UserProperties appsettings_1json__JsonSchema="" />
    </VisualStudio>
  </ProjectExtensions>

</Project>
